export const jobs = [
  {
    id: 1,
    title: "Frontend Developer",
    company: "Google",
    location: "Lahore, Pakistan",
    type: "full-time",
    experience: "mid",
    category: "technology",
    salary: { min: 800000, max: 1200000, currency: "PKR", period: "year" },
    postedAt: "Feb 8, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Hybrid",
    employmentType: "Full-time",
    openings: 3,
    department: "Engineering",
    industry: "Internet",
    companySize: "10,000+",
    aboutCompany:
      "Google builds products and platforms that help billions of people across the globe. The Lahore team focuses on high-impact consumer and cloud experiences.",
    description:
      "Join a cross-functional product squad to design, build, and ship performant web experiences used at massive scale. You will own features end to end, from discovery to rollout.",
    responsibilities: [
      "Build accessible, responsive UI components using React and modern CSS",
      "Collaborate with design and product to deliver pixel-accurate interfaces",
      "Improve performance by optimizing rendering and bundle size",
      "Write maintainable, well-tested code and documentation",
    ],
    requirements: [
      "3+ years of experience building production web apps",
      "Strong knowledge of React, JavaScript, and CSS",
      "Experience with performance profiling and accessibility",
      "Ability to work across the stack with backend partners",
    ],
    niceToHave: [
      "Experience with Next.js and design systems",
      "Familiarity with experimentation and analytics tooling",
    ],
    skills: [
      "React",
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "Web Performance",
    ],
    benefits: [
      "Health and wellness coverage",
      "Learning budget and mentorship",
      "Flexible working hours",
      "Annual bonus and equity",
    ],
    perks: ["Free meals", "On-site gym", "Commuter support"],
    applyBy: "Feb 28, 2026",
    recruiterEmail: "talent@google.com",
  },
  {
    id: 2,
    title: "UI/UX Designer",
    company: "Figma",
    location: "Remote (Pakistan)",
    type: "full-time",
    experience: "junior",
    category: "design",
    salary: { min: 650000, max: 950000, currency: "PKR", period: "year" },
    postedAt: "Feb 9, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Remote",
    employmentType: "Full-time",
    openings: 2,
    department: "Design",
    industry: "Software",
    companySize: "1,000+",
    aboutCompany:
      "Figma enables teams to design, prototype, and collaborate in a browser-based design platform loved by product teams worldwide.",
    description:
      "Create elegant interfaces for collaboration-first tools. You will work closely with product and research to translate insights into delightful user journeys.",
    responsibilities: [
      "Design user flows, wireframes, and polished UI screens",
      "Run usability tests and synthesize insights",
      "Contribute to design systems and component libraries",
      "Partner with engineers to ensure design quality",
    ],
    requirements: [
      "1+ years of product design experience or strong portfolio",
      "Expertise in Figma and prototyping",
      "Understanding of design systems and accessibility",
      "Ability to communicate design rationale clearly",
    ],
    niceToHave: [
      "Experience with motion design",
      "Familiarity with developer handoff workflows",
    ],
    skills: ["Product Design", "Prototyping", "Research", "Design Systems"],
    benefits: [
      "Remote-first equipment stipend",
      "Wellness allowance",
      "Learning and conference budget",
    ],
    perks: ["Home office stipend", "Team offsites"],
    applyBy: "Mar 3, 2026",
    recruiterEmail: "design@figma.com",
  },
  {
    id: 3,
    title: "Backend Engineer",
    company: "Amazon",
    location: "Islamabad, Pakistan",
    type: "full-time",
    experience: "senior",
    category: "technology",
    salary: { min: 1200000, max: 1700000, currency: "PKR", period: "year" },
    postedAt: "Feb 7, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Onsite",
    employmentType: "Full-time",
    openings: 4,
    department: "Engineering",
    industry: "E-commerce",
    companySize: "10,000+",
    aboutCompany:
      "Amazon builds scalable systems that serve millions of customers and sellers. The Islamabad team powers critical services and data pipelines.",
    description:
      "Design and implement distributed services, ensuring reliability, security, and observability. Work with product and data teams to ship impactful features.",
    responsibilities: [
      "Develop scalable APIs and backend services",
      "Own service reliability and operational excellence",
      "Design data models and storage strategies",
      "Mentor engineers and drive code quality",
    ],
    requirements: [
      "5+ years of backend engineering experience",
      "Strong knowledge of Java, Go, or Python",
      "Experience with microservices and AWS",
      "Solid understanding of data modeling",
    ],
    niceToHave: ["Experience with event-driven systems", "Kubernetes"],
    skills: ["Java", "AWS", "Microservices", "System Design"],
    benefits: [
      "Health coverage for family",
      "RSUs and performance bonus",
      "Relocation support",
    ],
    perks: ["Cafeteria", "Transport shuttle"],
    applyBy: "Feb 26, 2026",
    recruiterEmail: "techcareers@amazon.com",
  },
  {
    id: 4,
    title: "Marketing Executive",
    company: "HubSpot",
    location: "Remote (Pakistan)",
    type: "contract",
    experience: "mid",
    category: "marketing",
    salary: { min: 500000, max: 750000, currency: "PKR", period: "year" },
    postedAt: "Feb 5, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Remote",
    employmentType: "Contract",
    openings: 1,
    department: "Marketing",
    industry: "SaaS",
    companySize: "5,000+",
    aboutCompany:
      "HubSpot helps businesses grow better with marketing, sales, and service software. The marketing org drives global demand generation.",
    description:
      "Plan and execute multi-channel campaigns, partnering with content, design, and sales to increase pipeline and customer engagement.",
    responsibilities: [
      "Launch integrated marketing campaigns",
      "Manage performance metrics and reporting",
      "Coordinate with agencies and internal teams",
      "Optimize conversion funnels",
    ],
    requirements: [
      "3+ years in B2B marketing",
      "Experience with marketing automation tools",
      "Strong analytical and copywriting skills",
    ],
    niceToHave: ["SaaS marketing background", "SEO knowledge"],
    skills: ["Campaigns", "Analytics", "Content", "Marketing Ops"],
    benefits: ["Flexible schedules", "Remote work stipend"],
    perks: ["Team retreats"],
    applyBy: "Mar 1, 2026",
    recruiterEmail: "marketing@hubspot.com",
  },
  {
    id: 5,
    title: "Sales Manager",
    company: "Salesforce",
    location: "Karachi, Pakistan",
    type: "full-time",
    experience: "lead",
    category: "sales",
    salary: { min: 1400000, max: 2000000, currency: "PKR", period: "year" },
    postedAt: "Feb 6, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Hybrid",
    employmentType: "Full-time",
    openings: 2,
    department: "Sales",
    industry: "Enterprise Software",
    companySize: "10,000+",
    aboutCompany:
      "Salesforce is a leader in CRM and cloud solutions. The Karachi sales org partners with enterprise customers across Pakistan.",
    description:
      "Lead a team of account executives, drive pipeline creation, and close high-impact enterprise deals while mentoring and coaching sellers.",
    responsibilities: [
      "Manage and develop a high-performing sales team",
      "Forecast revenue and pipeline accurately",
      "Build relationships with enterprise stakeholders",
      "Collaborate with marketing and customer success",
    ],
    requirements: [
      "7+ years in B2B sales and 2+ years in people management",
      "Proven track record closing enterprise deals",
      "Strong negotiation and stakeholder management skills",
    ],
    niceToHave: ["CRM platform experience", "Industry network"],
    skills: ["Enterprise Sales", "Leadership", "Forecasting"],
    benefits: ["Health insurance", "Sales incentives", "Career coaching"],
    perks: ["Team events", "Wellness programs"],
    applyBy: "Mar 5, 2026",
    recruiterEmail: "sales@trailblazers.com",
  },
  {
    id: 6,
    title: "HR Business Partner",
    company: "Deloitte",
    location: "Islamabad, Pakistan",
    type: "full-time",
    experience: "mid",
    category: "hr",
    salary: { min: 750000, max: 1100000, currency: "PKR", period: "year" },
    postedAt: "Feb 4, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Onsite",
    employmentType: "Full-time",
    openings: 1,
    department: "People",
    industry: "Consulting",
    companySize: "10,000+",
    aboutCompany:
      "Deloitte delivers industry-leading audit, consulting, tax, and advisory services with a people-first culture.",
    description:
      "Partner with business leaders to drive talent strategy, culture, and organizational effectiveness across teams.",
    responsibilities: [
      "Advise leadership on people strategy",
      "Support performance management and engagement",
      "Lead workforce planning initiatives",
      "Coach managers on employee relations",
    ],
    requirements: [
      "4+ years in HRBP or talent roles",
      "Experience working with senior leadership",
      "Strong communication and conflict resolution skills",
    ],
    niceToHave: ["Consulting experience", "Change management"],
    skills: ["HR Strategy", "Coaching", "Org Design"],
    benefits: ["Comprehensive insurance", "Learning programs"],
    perks: ["Mentorship", "Flexible leave"],
    applyBy: "Mar 2, 2026",
    recruiterEmail: "people@deloitte.com",
  },
  {
    id: 7,
    title: "Finance Analyst",
    company: "JP Morgan",
    location: "Lahore, Pakistan",
    type: "full-time",
    experience: "entry",
    category: "finance",
    salary: { min: 500000, max: 800000, currency: "PKR", period: "year" },
    postedAt: "Feb 3, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Onsite",
    employmentType: "Full-time",
    openings: 3,
    department: "Finance",
    industry: "Financial Services",
    companySize: "10,000+",
    aboutCompany:
      "JP Morgan delivers global financial services, supporting clients with banking, asset management, and investment solutions.",
    description:
      "Support financial planning, reporting, and analysis for business units. Gain exposure to strategic decision-making and budgeting.",
    responsibilities: [
      "Prepare monthly financial reports",
      "Analyze trends and variances",
      "Assist with budgeting and forecasting",
      "Partner with operations teams",
    ],
    requirements: [
      "1+ years in finance or strong academic background",
      "Advanced Excel and analytical skills",
      "Knowledge of financial statements",
    ],
    niceToHave: ["Exposure to SQL or BI tools"],
    skills: ["Financial Analysis", "Excel", "Forecasting"],
    benefits: ["Insurance", "Learning stipend", "Performance bonus"],
    perks: ["Cafeteria", "Employee discounts"],
    applyBy: "Mar 6, 2026",
    recruiterEmail: "finance@jpmorgan.com",
  },
  {
    id: 8,
    title: "Customer Support Executive",
    company: "Freshworks",
    location: "Multan, Pakistan",
    type: "part-time",
    experience: "entry",
    category: "support",
    salary: { min: 350000, max: 520000, currency: "PKR", period: "year" },
    postedAt: "Feb 8, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Hybrid",
    employmentType: "Part-time",
    openings: 5,
    department: "Support",
    industry: "Customer Experience",
    companySize: "5,000+",
    aboutCompany:
      "Freshworks builds customer support and CRM tools that help businesses deliver outstanding service.",
    description:
      "Provide fast and empathetic support to global customers through chat and email, while documenting common issues and solutions.",
    responsibilities: [
      "Resolve customer inquiries within SLA",
      "Document solutions in knowledge base",
      "Collaborate with product and engineering",
    ],
    requirements: [
      "Strong communication skills",
      "Comfortable with shift schedules",
      "Problem-solving mindset",
    ],
    niceToHave: ["Experience with support ticketing tools"],
    skills: ["Customer Support", "Communication", "CRM"],
    benefits: ["Health coverage", "Wellness stipend"],
    perks: ["Cafeteria", "Team events"],
    applyBy: "Feb 25, 2026",
    recruiterEmail: "supportcareers@freshworks.com",
  },
  {
    id: 9,
    title: "Operations Manager",
    company: "Uber",
    location: "Peshawar, Pakistan",
    type: "full-time",
    experience: "senior",
    category: "operations",
    salary: { min: 1100000, max: 1600000, currency: "PKR", period: "year" },
    postedAt: "Feb 7, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Onsite",
    employmentType: "Full-time",
    openings: 2,
    department: "Operations",
    industry: "Mobility",
    companySize: "10,000+",
    aboutCompany:
      "Uber reimagines the way the world moves. The Peshawar ops team powers driver and rider success across markets.",
    description:
      "Own operational KPIs, run experiments, and scale processes to improve marketplace efficiency and customer satisfaction.",
    responsibilities: [
      "Manage operational programs and dashboards",
      "Lead cross-functional initiatives",
      "Optimize supply-demand balance",
      "Coach and develop team members",
    ],
    requirements: [
      "5+ years in operations or program management",
      "Strong analytical and stakeholder skills",
      "Experience with SQL or data tools",
    ],
    niceToHave: ["Marketplace experience", "Process automation"],
    skills: ["Operations", "Analytics", "Program Management"],
    benefits: ["Health insurance", "Equity", "Learning budget"],
    perks: ["Commuter allowance", "Snacks"],
    applyBy: "Mar 4, 2026",
    recruiterEmail: "ops@uber.com",
  },
  {
    id: 10,
    title: "Software Engineering Intern",
    company: "Microsoft",
    location: "Remote (Pakistan)",
    type: "internship",
    experience: "entry",
    category: "technology",
    salary: { min: 40000, max: 60000, currency: "PKR", period: "month" },
    postedAt: "Feb 10, 2026",
    logo: "/companies/company-placeholder.svg",
    workMode: "Remote",
    employmentType: "Internship",
    openings: 6,
    department: "Engineering",
    industry: "Software",
    companySize: "10,000+",
    aboutCompany:
      "Microsoft empowers every person and organization to achieve more. The internship program focuses on learning and mentorship.",
    description:
      "Work with engineers to build and ship features, learn industry best practices, and contribute to real customer-facing products.",
    responsibilities: [
      "Ship features in a production codebase",
      "Write tests and document changes",
      "Participate in code reviews and standups",
    ],
    requirements: [
      "Currently pursuing a degree in CS or related field",
      "Solid fundamentals in programming",
      "Ability to learn quickly and collaborate",
    ],
    niceToHave: ["Personal projects or open-source contributions"],
    skills: ["JavaScript", "C#", "Problem Solving"],
    benefits: ["Mentorship", "Learning stipend"],
    perks: ["Remote equipment kit"],
    applyBy: "Mar 8, 2026",
    recruiterEmail: "interns@microsoft.com",
  },
];

export const getJobById = (id) => {
  if (id === null || id === undefined) return undefined;
  return jobs.find((job) => String(job.id) === String(id));
};
